RegisterNetEvent('__GMT_callback:client')
AddEventHandler('__GMT_callback:client',function(aJ,...)
    local aK=promise.new()
    TriggerEvent(string.format('c__GMT_callback:%s',aJ),function(...)
        aK:resolve({...})end,...)
    local aL=Citizen.Await(aK)
    TriggerServerEvent(string.format('__GMT_callback:server:%s:%s',aJ,...),table.unpack(aL))
end)
GMT.TriggerServerCallback=function(aJ,...)
    assert(type(aJ)=='string','Invalid Lua type at argument #1, expected string, got '..type(aJ))
    local aK=promise.new()
    local aM=GetGameTimer()
    RegisterNetEvent(string.format('__GMT_callback:client:%s:%s',aJ,aM))
    local aN=AddEventHandler(string.format('__GMT_callback:client:%s:%s',aJ,aM),function(...)
        aK:resolve({...})
    end)
    TriggerServerEvent('__GMT_callback:server',aJ,aM,...)
    local aL=Citizen.Await(aK)
    RemoveEventHandler(aN)
    return table.unpack(aL)
end
GMT.RegisterClientCallback=function(aJ,aO)
    assert(type(aJ)=='string','Invalid Lua type at argument #1, expected string, got '..type(aJ))
    assert(type(aO)=='function','Invalid Lua type at argument #2, expected function, got '..type(aO))
    AddEventHandler(string.format('c__GMT_callback:%s',aJ),function(aP,...)
        aP(aO(...))
    end)
end